ame: Check PR into release
on:
  pull_request:
    branches:
      - release/*

jobs:
  check-tag-origin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Get branch tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null)
          if [ -z "$latest_tag" || [[ "$latest_tag" == r* ]]; then
            echo "Error: not tags seems this branch was not created from release branch!!!!"
            exit 1
          fi
          
          echo "Latest tag: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Get base branch tag
        id: get_base_branch_tag
        run: |
          base_branch_tag=$(git tag --merged origin/${{github.base_ref}} | sort -V | tail -n 1)
          if [ -z "$base_branch_tag" ]; then
            echo "Error: The release branch does not have an associated tag. This may indicate it is not a release branch or that a tag is missing"
            exit 1
          fi
          
          echo "Branch name: $base_branch_tag"
          echo "base_branch_tag=$base_branch_tag" >> $GITHUB_ENV

      - name: Compare tags
        run: |
          tag_version=$(echo "$latest_tag" | tr -d 'v.')
          branch_version=$(echo "$base_branch_tag" | tr -d 'v.')
          
          if [ "$tag_version" -le "$branch_version" ]; then
             echo "OK"
          else
             echo "Error: Tag version ($latest_tag) is greater than branch tag ($base_branch_tag)."
             exit 1
          fi


      - name: Allow merge
        run: echo "Branch is valid to be merge in release"