name: Nigel CI/CD

on:
  workflow_dispatch

jobs:
  build: 
    runs-on: ubuntu-latest
    env:
      node_version: "18.19.1"

    steps:
    - uses: actions/checkout@v4

    - name: Node.js ${{ env.node_version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node_version}}

    - name: build package
      run: |
          yarn
          yarn build
      


