name: Check PR into release
on:
  pull_request:
    branches:
      - release/*

jobs:
  check-tag-origin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Check does brnach has tags
        run: |
          if [ -z "$(git tag)" ]; then
            echo "Error: seems this branch was not created from release branch!!!!"
            exit 1
          fi

      - name: Check PR
        run: |
            latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) 2> /dev/null || echo "v0.0.0")
            echo "Latest tag: $latest_tag"
            echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Get branch name
        id: get_branch_name
        run: | 
            branch_name=$(git describe --tags $(git merge-base ${{github.base_ref}} HEAD) 2>/dev/null || echo "none")
            echo "Branch name: $branch_name"
            echo "branch_name=$branch_name" >> $GITHUB_ENV

      - name: Allow merge
        run: echo "Branch is valid to be merge in release"